-- Fleet Data Pipeline - PostgreSQL schema

-- 1. Raw/processed telemetry events coming from the streaming pipeline.
CREATE TABLE IF NOT EXISTS telemetry_events (
    id BIGSERIAL PRIMARY KEY,
    trip_id VARCHAR(20),
    driver_id VARCHAR(20) NOT NULL,
    vehicle_id VARCHAR(20) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    speed DOUBLE PRECISION NOT NULL CHECK (speed >= 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('idle', 'enroute', 'on_trip')),
    fare NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (fare >= 0),
    event_time TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_telemetry_trip_id
    ON telemetry_events (trip_id);

CREATE INDEX IF NOT EXISTS idx_telemetry_driver_time
    ON telemetry_events (driver_id, event_time DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_vehicle_time
    ON telemetry_events (vehicle_id, event_time DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_event_time
    ON telemetry_events (event_time DESC);

-- 2. Per-trip analytics produced by Spark Structured Streaming.
-- Person 2 can upsert one row per trip into this table.
CREATE TABLE IF NOT EXISTS trip_analytics (
    trip_id VARCHAR(20) PRIMARY KEY,
    driver_id VARCHAR(20) NOT NULL,
    vehicle_id VARCHAR(20) NOT NULL,
    avg_speed DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (avg_speed >= 0),
    max_speed DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (max_speed >= 0),
    final_fare NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (final_fare >= 0),
    trip_status VARCHAR(20) NOT NULL CHECK (trip_status IN ('enroute', 'on_trip', 'completed')),
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_trip_analytics_driver
    ON trip_analytics (driver_id);

CREATE INDEX IF NOT EXISTS idx_trip_analytics_vehicle
    ON trip_analytics (vehicle_id);

CREATE INDEX IF NOT EXISTS idx_trip_analytics_start_time
    ON trip_analytics (start_time DESC);

-- 3. Batch expense data loaded by Airflow.
CREATE TABLE IF NOT EXISTS expenses (
    expense_id VARCHAR(30) PRIMARY KEY,
    vehicle_id VARCHAR(20) NOT NULL,
    expense_type VARCHAR(50) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    expense_date DATE NOT NULL,
    description TEXT,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_expenses_vehicle_date
    ON expenses (vehicle_id, expense_date DESC);

CREATE INDEX IF NOT EXISTS idx_expenses_date
    ON expenses (expense_date DESC);

-- 4. Daily aggregate generated by the Airflow batch workflow.
CREATE TABLE IF NOT EXISTS daily_fleet_summary (
    summary_date DATE PRIMARY KEY,
    total_trips INTEGER NOT NULL DEFAULT 0 CHECK (total_trips >= 0),
    completed_trips INTEGER NOT NULL DEFAULT 0 CHECK (completed_trips >= 0),
    average_speed DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (average_speed >= 0),
    total_revenue NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (total_revenue >= 0),
    total_expenses NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (total_expenses >= 0),
    net_revenue NUMERIC(14, 2) NOT NULL DEFAULT 0,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
